// scripts/fetch-fonts.js  —  pnpm fonts
//
// Downloads the Fraunces + JetBrains Mono woff2 files Google serves and writes
// them into public/fonts/, plus the matching @font-face rules into
// src/fonts.css. Run this again to pick up a font revision; both outputs are
// committed so a normal build (and a Vercel deploy) never touches the network.
//
// Why self-host at all: as a <link> to fonts.googleapis.com the stylesheet is
// render-blocking *and* cross-origin, so the browser pays DNS + TCP + TLS to a
// third party before it can paint anything — expensive on a phone connection,
// where it was measured as the gate on FCP. Served from our own origin the
// bytes arrive on the connection that is already open.
//
// Only the `latin` and `latin-ext` subsets are kept. The es/pt locales sit
// inside latin (U+0000-00FF covers ñ, ã, ç, õ) and zh falls back to a system
// CJK face either way, because neither of these families ships Han glyphs.
// Keeping latin-ext costs nothing at runtime: unicode-range makes the browser
// fetch a subset only when the page actually uses a character from it.
//
// The filenames below encode family/style/weight/subset, and this script writes
// a new name whenever any of those change, so the bytes behind a given URL never
// change. That is what makes the `immutable` Cache-Control on /fonts/*.woff2 in
// vercel.json safe — without it Vercel serves them must-revalidate and every
// repeat visit pays a round trip per face. vercel.json is plain JSON with no
// room for a comment, so the reasoning lives here.
import { mkdir, writeFile } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900' +
  '&family=JetBrains+Mono:wght@400;500;600&display=swap';

// Google varies the response on User-Agent: an unknown agent gets ttf and the
// full unicode set, a modern Chrome gets woff2 split by unicode-range.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const KEEP = new Set(['latin', 'latin-ext']);
const OUT_DIR = 'public/fonts';
const CSS_OUT = 'src/fonts.css';

const res = await fetch(CSS_URL, { headers: { 'user-agent': UA } });
if (!res.ok) throw new Error(`fetch-fonts: Google Fonts returned ${res.status}`);
const css = await res.text();

// Each @font-face is preceded by a `/* subset */` comment naming its subset.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
if (blocks.length === 0) throw new Error('fetch-fonts: parsed no @font-face blocks');

await mkdir(OUT_DIR, { recursive: true });

const field = (block, name) => block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim();
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const rules = [];
let kept = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;

  const family = field(block, 'font-family').replace(/['"]/g, '');
  const style = field(block, 'font-style');
  const weight = field(block, 'font-weight');
  const range = field(block, 'unicode-range');
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!url) throw new Error(`fetch-fonts: no woff2 url in ${family} ${style} ${weight}`);

  // Variable faces carry a `100 900` range; collapse it for the filename.
  const weightSlug = weight.includes(' ') ? 'var' : weight;
  const file = `${slug(family)}-${style}-${weightSlug}-${subset}.woff2`;

  const bin = await fetch(url, { headers: { 'user-agent': UA } });
  if (!bin.ok) throw new Error(`fetch-fonts: ${file} returned ${bin.status}`);
  const bytes = Buffer.from(await bin.arrayBuffer());
  await writeFile(`${OUT_DIR}/${file}`, bytes);
  console.log(`${file.padEnd(44)} ${String(Math.round(bytes.length / 1024)).padStart(4)}KB`);
  kept++;

  rules.push(
    `/* ${subset} */\n@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      `  unicode-range: ${range};\n}`,
  );
}

const header =
  `/* Generated by scripts/fetch-fonts.js (\`pnpm fonts\`) — do not hand-edit.\n` +
  `   Self-hosted so the render-blocking stylesheet is same-origin: a phone no\n` +
  `   longer pays a third-party DNS + TCP + TLS handshake before first paint.\n` +
  `   Only latin and latin-ext are shipped; unicode-range keeps latin-ext from\n` +
  `   being fetched unless the page uses a character from it. */\n`;

await writeFile(CSS_OUT, `${header}\n${rules.join('\n\n')}\n`, 'utf-8');
console.log(`\n${kept} faces -> ${OUT_DIR}/, rules -> ${CSS_OUT}`);
